version: '3.1'
services:
  careservice:
    network_mode: bridge
    container_name: careservice
    image: bogdannaida/care-service:latest
    build: ./
    ports:
      - "8087:8087"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=careservice
      - DB_SERVER=postgresqldb-care
    links:
      - postgresqldb-care

  postgresqldb-care:
    network_mode: bridge
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=careservice
    volumes:
      - postgres-data-care:/home/bogdannaida/Projects/IntelliJ-projects/Volumes/
volumes:
  postgres-data-care: